runtime: nodejs
env: flex

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'la-supreme'
  DATABASE_USERNAME: 'supreme-pg'
  DATABASE_PASSWORD: 'vP5cxxrzIDcbNkg4'
  INSTANCE_CONNECTION_NAME: '/cloudsql/supreme-304316:europe-west3:supreme-pg'

beta_settings:
  cloud_sql_instances: 'supreme-304316:europe-west3:supreme-pg'
